language: java
mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
